export const CHANGE_PREDICTION = "CHANGE_PREDICTION";
export const HANDLE_USER_INPUT = "HANDLE_USER_INPUT";
export const CLEAR_USER_INPUT = "CLEAR_USER_INPUT";
export const TEMPORARY_SET_PREDICTION_TO_EMPTY_STRING =
  "TEMPORARY_SET_PREDICTION_TO_EMPTY_STRING";
export const SET_FADING = "SET_FADING";
